language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - th3str4p@gmail.com
    on_success: always
    on_failure: always
node_js:
  - '9'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  target_branch: master
  on:
    branch: dev
